// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBtoMapperQMsg.proto

package gmapper.mysql;

public final class ProtobufMapperQMsg {
  private ProtobufMapperQMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MapperQMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string CRUDaction = 1;
    /**
     * <code>optional string CRUDaction = 1;</code>
     */
    boolean hasCRUDaction();
    /**
     * <code>optional string CRUDaction = 1;</code>
     */
    java.lang.String getCRUDaction();
    /**
     * <code>optional string CRUDaction = 1;</code>
     */
    com.google.protobuf.ByteString
        getCRUDactionBytes();

    // optional string adaptor_type = 2;
    /**
     * <code>optional string adaptor_type = 2;</code>
     */
    boolean hasAdaptorType();
    /**
     * <code>optional string adaptor_type = 2;</code>
     */
    java.lang.String getAdaptorType();
    /**
     * <code>optional string adaptor_type = 2;</code>
     */
    com.google.protobuf.ByteString
        getAdaptorTypeBytes();

    // optional int32 adaptor_id = 3;
    /**
     * <code>optional int32 adaptor_id = 3;</code>
     */
    boolean hasAdaptorId();
    /**
     * <code>optional int32 adaptor_id = 3;</code>
     */
    int getAdaptorId();

    // optional int32 mapperId = 4;
    /**
     * <code>optional int32 mapperId = 4;</code>
     */
    boolean hasMapperId();
    /**
     * <code>optional int32 mapperId = 4;</code>
     */
    int getMapperId();

    // repeated string field_name = 5;
    /**
     * <code>repeated string field_name = 5;</code>
     */
    java.util.List<java.lang.String>
    getFieldNameList();
    /**
     * <code>repeated string field_name = 5;</code>
     */
    int getFieldNameCount();
    /**
     * <code>repeated string field_name = 5;</code>
     */
    java.lang.String getFieldName(int index);
    /**
     * <code>repeated string field_name = 5;</code>
     */
    com.google.protobuf.ByteString
        getFieldNameBytes(int index);

    // repeated string field_value = 6;
    /**
     * <code>repeated string field_value = 6;</code>
     */
    java.util.List<java.lang.String>
    getFieldValueList();
    /**
     * <code>repeated string field_value = 6;</code>
     */
    int getFieldValueCount();
    /**
     * <code>repeated string field_value = 6;</code>
     */
    java.lang.String getFieldValue(int index);
    /**
     * <code>repeated string field_value = 6;</code>
     */
    com.google.protobuf.ByteString
        getFieldValueBytes(int index);

    // repeated string field_type = 7;
    /**
     * <code>repeated string field_type = 7;</code>
     */
    java.util.List<java.lang.String>
    getFieldTypeList();
    /**
     * <code>repeated string field_type = 7;</code>
     */
    int getFieldTypeCount();
    /**
     * <code>repeated string field_type = 7;</code>
     */
    java.lang.String getFieldType(int index);
    /**
     * <code>repeated string field_type = 7;</code>
     */
    com.google.protobuf.ByteString
        getFieldTypeBytes(int index);
  }
  /**
   * Protobuf type {@code gmapper.mysql.MapperQMsg}
   */
  public static final class MapperQMsg extends
      com.google.protobuf.GeneratedMessage
      implements MapperQMsgOrBuilder {
    // Use MapperQMsg.newBuilder() to construct.
    private MapperQMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MapperQMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MapperQMsg defaultInstance;
    public static MapperQMsg getDefaultInstance() {
      return defaultInstance;
    }

    public MapperQMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MapperQMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              cRUDaction_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              adaptorType_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              adaptorId_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              mapperId_ = input.readInt32();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                fieldName_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              fieldName_.add(input.readBytes());
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                fieldValue_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              fieldValue_.add(input.readBytes());
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                fieldType_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000040;
              }
              fieldType_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          fieldName_ = new com.google.protobuf.UnmodifiableLazyStringList(fieldName_);
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          fieldValue_ = new com.google.protobuf.UnmodifiableLazyStringList(fieldValue_);
        }
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          fieldType_ = new com.google.protobuf.UnmodifiableLazyStringList(fieldType_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gmapper.mysql.ProtobufMapperQMsg.internal_static_gmapper_mysql_MapperQMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gmapper.mysql.ProtobufMapperQMsg.internal_static_gmapper_mysql_MapperQMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gmapper.mysql.ProtobufMapperQMsg.MapperQMsg.class, gmapper.mysql.ProtobufMapperQMsg.MapperQMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<MapperQMsg> PARSER =
        new com.google.protobuf.AbstractParser<MapperQMsg>() {
      public MapperQMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MapperQMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MapperQMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string CRUDaction = 1;
    public static final int CRUDACTION_FIELD_NUMBER = 1;
    private java.lang.Object cRUDaction_;
    /**
     * <code>optional string CRUDaction = 1;</code>
     */
    public boolean hasCRUDaction() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string CRUDaction = 1;</code>
     */
    public java.lang.String getCRUDaction() {
      java.lang.Object ref = cRUDaction_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cRUDaction_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string CRUDaction = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCRUDactionBytes() {
      java.lang.Object ref = cRUDaction_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cRUDaction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string adaptor_type = 2;
    public static final int ADAPTOR_TYPE_FIELD_NUMBER = 2;
    private java.lang.Object adaptorType_;
    /**
     * <code>optional string adaptor_type = 2;</code>
     */
    public boolean hasAdaptorType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string adaptor_type = 2;</code>
     */
    public java.lang.String getAdaptorType() {
      java.lang.Object ref = adaptorType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          adaptorType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string adaptor_type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAdaptorTypeBytes() {
      java.lang.Object ref = adaptorType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        adaptorType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 adaptor_id = 3;
    public static final int ADAPTOR_ID_FIELD_NUMBER = 3;
    private int adaptorId_;
    /**
     * <code>optional int32 adaptor_id = 3;</code>
     */
    public boolean hasAdaptorId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 adaptor_id = 3;</code>
     */
    public int getAdaptorId() {
      return adaptorId_;
    }

    // optional int32 mapperId = 4;
    public static final int MAPPERID_FIELD_NUMBER = 4;
    private int mapperId_;
    /**
     * <code>optional int32 mapperId = 4;</code>
     */
    public boolean hasMapperId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 mapperId = 4;</code>
     */
    public int getMapperId() {
      return mapperId_;
    }

    // repeated string field_name = 5;
    public static final int FIELD_NAME_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList fieldName_;
    /**
     * <code>repeated string field_name = 5;</code>
     */
    public java.util.List<java.lang.String>
        getFieldNameList() {
      return fieldName_;
    }
    /**
     * <code>repeated string field_name = 5;</code>
     */
    public int getFieldNameCount() {
      return fieldName_.size();
    }
    /**
     * <code>repeated string field_name = 5;</code>
     */
    public java.lang.String getFieldName(int index) {
      return fieldName_.get(index);
    }
    /**
     * <code>repeated string field_name = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFieldNameBytes(int index) {
      return fieldName_.getByteString(index);
    }

    // repeated string field_value = 6;
    public static final int FIELD_VALUE_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList fieldValue_;
    /**
     * <code>repeated string field_value = 6;</code>
     */
    public java.util.List<java.lang.String>
        getFieldValueList() {
      return fieldValue_;
    }
    /**
     * <code>repeated string field_value = 6;</code>
     */
    public int getFieldValueCount() {
      return fieldValue_.size();
    }
    /**
     * <code>repeated string field_value = 6;</code>
     */
    public java.lang.String getFieldValue(int index) {
      return fieldValue_.get(index);
    }
    /**
     * <code>repeated string field_value = 6;</code>
     */
    public com.google.protobuf.ByteString
        getFieldValueBytes(int index) {
      return fieldValue_.getByteString(index);
    }

    // repeated string field_type = 7;
    public static final int FIELD_TYPE_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList fieldType_;
    /**
     * <code>repeated string field_type = 7;</code>
     */
    public java.util.List<java.lang.String>
        getFieldTypeList() {
      return fieldType_;
    }
    /**
     * <code>repeated string field_type = 7;</code>
     */
    public int getFieldTypeCount() {
      return fieldType_.size();
    }
    /**
     * <code>repeated string field_type = 7;</code>
     */
    public java.lang.String getFieldType(int index) {
      return fieldType_.get(index);
    }
    /**
     * <code>repeated string field_type = 7;</code>
     */
    public com.google.protobuf.ByteString
        getFieldTypeBytes(int index) {
      return fieldType_.getByteString(index);
    }

    private void initFields() {
      cRUDaction_ = "";
      adaptorType_ = "";
      adaptorId_ = 0;
      mapperId_ = 0;
      fieldName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      fieldValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      fieldType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCRUDactionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAdaptorTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, adaptorId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, mapperId_);
      }
      for (int i = 0; i < fieldName_.size(); i++) {
        output.writeBytes(5, fieldName_.getByteString(i));
      }
      for (int i = 0; i < fieldValue_.size(); i++) {
        output.writeBytes(6, fieldValue_.getByteString(i));
      }
      for (int i = 0; i < fieldType_.size(); i++) {
        output.writeBytes(7, fieldType_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCRUDactionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAdaptorTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, adaptorId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, mapperId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < fieldName_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(fieldName_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getFieldNameList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < fieldValue_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(fieldValue_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getFieldValueList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < fieldType_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(fieldType_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getFieldTypeList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gmapper.mysql.ProtobufMapperQMsg.MapperQMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gmapper.mysql.ProtobufMapperQMsg.MapperQMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gmapper.mysql.ProtobufMapperQMsg.MapperQMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gmapper.mysql.ProtobufMapperQMsg.MapperQMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gmapper.mysql.ProtobufMapperQMsg.MapperQMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gmapper.mysql.ProtobufMapperQMsg.MapperQMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gmapper.mysql.ProtobufMapperQMsg.MapperQMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gmapper.mysql.ProtobufMapperQMsg.MapperQMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gmapper.mysql.ProtobufMapperQMsg.MapperQMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gmapper.mysql.ProtobufMapperQMsg.MapperQMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gmapper.mysql.ProtobufMapperQMsg.MapperQMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gmapper.mysql.MapperQMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements gmapper.mysql.ProtobufMapperQMsg.MapperQMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gmapper.mysql.ProtobufMapperQMsg.internal_static_gmapper_mysql_MapperQMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gmapper.mysql.ProtobufMapperQMsg.internal_static_gmapper_mysql_MapperQMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gmapper.mysql.ProtobufMapperQMsg.MapperQMsg.class, gmapper.mysql.ProtobufMapperQMsg.MapperQMsg.Builder.class);
      }

      // Construct using gmapper.mysql.ProtobufMapperQMsg.MapperQMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cRUDaction_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        adaptorType_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        adaptorId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        mapperId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        fieldName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        fieldValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        fieldType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gmapper.mysql.ProtobufMapperQMsg.internal_static_gmapper_mysql_MapperQMsg_descriptor;
      }

      public gmapper.mysql.ProtobufMapperQMsg.MapperQMsg getDefaultInstanceForType() {
        return gmapper.mysql.ProtobufMapperQMsg.MapperQMsg.getDefaultInstance();
      }

      public gmapper.mysql.ProtobufMapperQMsg.MapperQMsg build() {
        gmapper.mysql.ProtobufMapperQMsg.MapperQMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gmapper.mysql.ProtobufMapperQMsg.MapperQMsg buildPartial() {
        gmapper.mysql.ProtobufMapperQMsg.MapperQMsg result = new gmapper.mysql.ProtobufMapperQMsg.MapperQMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cRUDaction_ = cRUDaction_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.adaptorType_ = adaptorType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.adaptorId_ = adaptorId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.mapperId_ = mapperId_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          fieldName_ = new com.google.protobuf.UnmodifiableLazyStringList(
              fieldName_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.fieldName_ = fieldName_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          fieldValue_ = new com.google.protobuf.UnmodifiableLazyStringList(
              fieldValue_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.fieldValue_ = fieldValue_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          fieldType_ = new com.google.protobuf.UnmodifiableLazyStringList(
              fieldType_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.fieldType_ = fieldType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gmapper.mysql.ProtobufMapperQMsg.MapperQMsg) {
          return mergeFrom((gmapper.mysql.ProtobufMapperQMsg.MapperQMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gmapper.mysql.ProtobufMapperQMsg.MapperQMsg other) {
        if (other == gmapper.mysql.ProtobufMapperQMsg.MapperQMsg.getDefaultInstance()) return this;
        if (other.hasCRUDaction()) {
          bitField0_ |= 0x00000001;
          cRUDaction_ = other.cRUDaction_;
          onChanged();
        }
        if (other.hasAdaptorType()) {
          bitField0_ |= 0x00000002;
          adaptorType_ = other.adaptorType_;
          onChanged();
        }
        if (other.hasAdaptorId()) {
          setAdaptorId(other.getAdaptorId());
        }
        if (other.hasMapperId()) {
          setMapperId(other.getMapperId());
        }
        if (!other.fieldName_.isEmpty()) {
          if (fieldName_.isEmpty()) {
            fieldName_ = other.fieldName_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureFieldNameIsMutable();
            fieldName_.addAll(other.fieldName_);
          }
          onChanged();
        }
        if (!other.fieldValue_.isEmpty()) {
          if (fieldValue_.isEmpty()) {
            fieldValue_ = other.fieldValue_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureFieldValueIsMutable();
            fieldValue_.addAll(other.fieldValue_);
          }
          onChanged();
        }
        if (!other.fieldType_.isEmpty()) {
          if (fieldType_.isEmpty()) {
            fieldType_ = other.fieldType_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureFieldTypeIsMutable();
            fieldType_.addAll(other.fieldType_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gmapper.mysql.ProtobufMapperQMsg.MapperQMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gmapper.mysql.ProtobufMapperQMsg.MapperQMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string CRUDaction = 1;
      private java.lang.Object cRUDaction_ = "";
      /**
       * <code>optional string CRUDaction = 1;</code>
       */
      public boolean hasCRUDaction() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string CRUDaction = 1;</code>
       */
      public java.lang.String getCRUDaction() {
        java.lang.Object ref = cRUDaction_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          cRUDaction_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string CRUDaction = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCRUDactionBytes() {
        java.lang.Object ref = cRUDaction_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cRUDaction_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string CRUDaction = 1;</code>
       */
      public Builder setCRUDaction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        cRUDaction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string CRUDaction = 1;</code>
       */
      public Builder clearCRUDaction() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cRUDaction_ = getDefaultInstance().getCRUDaction();
        onChanged();
        return this;
      }
      /**
       * <code>optional string CRUDaction = 1;</code>
       */
      public Builder setCRUDactionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        cRUDaction_ = value;
        onChanged();
        return this;
      }

      // optional string adaptor_type = 2;
      private java.lang.Object adaptorType_ = "";
      /**
       * <code>optional string adaptor_type = 2;</code>
       */
      public boolean hasAdaptorType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string adaptor_type = 2;</code>
       */
      public java.lang.String getAdaptorType() {
        java.lang.Object ref = adaptorType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          adaptorType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string adaptor_type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAdaptorTypeBytes() {
        java.lang.Object ref = adaptorType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          adaptorType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string adaptor_type = 2;</code>
       */
      public Builder setAdaptorType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        adaptorType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string adaptor_type = 2;</code>
       */
      public Builder clearAdaptorType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        adaptorType_ = getDefaultInstance().getAdaptorType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string adaptor_type = 2;</code>
       */
      public Builder setAdaptorTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        adaptorType_ = value;
        onChanged();
        return this;
      }

      // optional int32 adaptor_id = 3;
      private int adaptorId_ ;
      /**
       * <code>optional int32 adaptor_id = 3;</code>
       */
      public boolean hasAdaptorId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 adaptor_id = 3;</code>
       */
      public int getAdaptorId() {
        return adaptorId_;
      }
      /**
       * <code>optional int32 adaptor_id = 3;</code>
       */
      public Builder setAdaptorId(int value) {
        bitField0_ |= 0x00000004;
        adaptorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 adaptor_id = 3;</code>
       */
      public Builder clearAdaptorId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        adaptorId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 mapperId = 4;
      private int mapperId_ ;
      /**
       * <code>optional int32 mapperId = 4;</code>
       */
      public boolean hasMapperId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 mapperId = 4;</code>
       */
      public int getMapperId() {
        return mapperId_;
      }
      /**
       * <code>optional int32 mapperId = 4;</code>
       */
      public Builder setMapperId(int value) {
        bitField0_ |= 0x00000008;
        mapperId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 mapperId = 4;</code>
       */
      public Builder clearMapperId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        mapperId_ = 0;
        onChanged();
        return this;
      }

      // repeated string field_name = 5;
      private com.google.protobuf.LazyStringList fieldName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFieldNameIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          fieldName_ = new com.google.protobuf.LazyStringArrayList(fieldName_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string field_name = 5;</code>
       */
      public java.util.List<java.lang.String>
          getFieldNameList() {
        return java.util.Collections.unmodifiableList(fieldName_);
      }
      /**
       * <code>repeated string field_name = 5;</code>
       */
      public int getFieldNameCount() {
        return fieldName_.size();
      }
      /**
       * <code>repeated string field_name = 5;</code>
       */
      public java.lang.String getFieldName(int index) {
        return fieldName_.get(index);
      }
      /**
       * <code>repeated string field_name = 5;</code>
       */
      public com.google.protobuf.ByteString
          getFieldNameBytes(int index) {
        return fieldName_.getByteString(index);
      }
      /**
       * <code>repeated string field_name = 5;</code>
       */
      public Builder setFieldName(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldNameIsMutable();
        fieldName_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_name = 5;</code>
       */
      public Builder addFieldName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldNameIsMutable();
        fieldName_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_name = 5;</code>
       */
      public Builder addAllFieldName(
          java.lang.Iterable<java.lang.String> values) {
        ensureFieldNameIsMutable();
        super.addAll(values, fieldName_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_name = 5;</code>
       */
      public Builder clearFieldName() {
        fieldName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_name = 5;</code>
       */
      public Builder addFieldNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldNameIsMutable();
        fieldName_.add(value);
        onChanged();
        return this;
      }

      // repeated string field_value = 6;
      private com.google.protobuf.LazyStringList fieldValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFieldValueIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          fieldValue_ = new com.google.protobuf.LazyStringArrayList(fieldValue_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string field_value = 6;</code>
       */
      public java.util.List<java.lang.String>
          getFieldValueList() {
        return java.util.Collections.unmodifiableList(fieldValue_);
      }
      /**
       * <code>repeated string field_value = 6;</code>
       */
      public int getFieldValueCount() {
        return fieldValue_.size();
      }
      /**
       * <code>repeated string field_value = 6;</code>
       */
      public java.lang.String getFieldValue(int index) {
        return fieldValue_.get(index);
      }
      /**
       * <code>repeated string field_value = 6;</code>
       */
      public com.google.protobuf.ByteString
          getFieldValueBytes(int index) {
        return fieldValue_.getByteString(index);
      }
      /**
       * <code>repeated string field_value = 6;</code>
       */
      public Builder setFieldValue(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldValueIsMutable();
        fieldValue_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_value = 6;</code>
       */
      public Builder addFieldValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldValueIsMutable();
        fieldValue_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_value = 6;</code>
       */
      public Builder addAllFieldValue(
          java.lang.Iterable<java.lang.String> values) {
        ensureFieldValueIsMutable();
        super.addAll(values, fieldValue_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_value = 6;</code>
       */
      public Builder clearFieldValue() {
        fieldValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_value = 6;</code>
       */
      public Builder addFieldValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldValueIsMutable();
        fieldValue_.add(value);
        onChanged();
        return this;
      }

      // repeated string field_type = 7;
      private com.google.protobuf.LazyStringList fieldType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFieldTypeIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          fieldType_ = new com.google.protobuf.LazyStringArrayList(fieldType_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated string field_type = 7;</code>
       */
      public java.util.List<java.lang.String>
          getFieldTypeList() {
        return java.util.Collections.unmodifiableList(fieldType_);
      }
      /**
       * <code>repeated string field_type = 7;</code>
       */
      public int getFieldTypeCount() {
        return fieldType_.size();
      }
      /**
       * <code>repeated string field_type = 7;</code>
       */
      public java.lang.String getFieldType(int index) {
        return fieldType_.get(index);
      }
      /**
       * <code>repeated string field_type = 7;</code>
       */
      public com.google.protobuf.ByteString
          getFieldTypeBytes(int index) {
        return fieldType_.getByteString(index);
      }
      /**
       * <code>repeated string field_type = 7;</code>
       */
      public Builder setFieldType(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldTypeIsMutable();
        fieldType_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_type = 7;</code>
       */
      public Builder addFieldType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldTypeIsMutable();
        fieldType_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_type = 7;</code>
       */
      public Builder addAllFieldType(
          java.lang.Iterable<java.lang.String> values) {
        ensureFieldTypeIsMutable();
        super.addAll(values, fieldType_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_type = 7;</code>
       */
      public Builder clearFieldType() {
        fieldType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_type = 7;</code>
       */
      public Builder addFieldTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldTypeIsMutable();
        fieldType_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gmapper.mysql.MapperQMsg)
    }

    static {
      defaultInstance = new MapperQMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gmapper.mysql.MapperQMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gmapper_mysql_MapperQMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gmapper_mysql_MapperQMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024PBtoMapperQMsg.proto\022\rgmapper.mysql\"\231\001" +
      "\n\nMapperQMsg\022\022\n\nCRUDaction\030\001 \001(\t\022\024\n\014adap" +
      "tor_type\030\002 \001(\t\022\022\n\nadaptor_id\030\003 \001(\005\022\020\n\010ma" +
      "pperId\030\004 \001(\005\022\022\n\nfield_name\030\005 \003(\t\022\023\n\013fiel" +
      "d_value\030\006 \003(\t\022\022\n\nfield_type\030\007 \003(\tB#\n\rgma" +
      "pper.mysqlB\022ProtobufMapperQMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_gmapper_mysql_MapperQMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_gmapper_mysql_MapperQMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gmapper_mysql_MapperQMsg_descriptor,
              new java.lang.String[] { "CRUDaction", "AdaptorType", "AdaptorId", "MapperId", "FieldName", "FieldValue", "FieldType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
