// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBAdminQMsg.proto

package gmapper.mysql;

public final class ProtobufAdminQMsg {
  private ProtobufAdminQMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AdminQMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string action = 1;
    /**
     * <code>optional string action = 1;</code>
     */
    boolean hasAction();
    /**
     * <code>optional string action = 1;</code>
     */
    java.lang.String getAction();
    /**
     * <code>optional string action = 1;</code>
     */
    com.google.protobuf.ByteString
        getActionBytes();

    // optional string adaptor_type = 2;
    /**
     * <code>optional string adaptor_type = 2;</code>
     */
    boolean hasAdaptorType();
    /**
     * <code>optional string adaptor_type = 2;</code>
     */
    java.lang.String getAdaptorType();
    /**
     * <code>optional string adaptor_type = 2;</code>
     */
    com.google.protobuf.ByteString
        getAdaptorTypeBytes();

    // optional int32 adaptor_id = 3;
    /**
     * <code>optional int32 adaptor_id = 3;</code>
     */
    boolean hasAdaptorId();
    /**
     * <code>optional int32 adaptor_id = 3;</code>
     */
    int getAdaptorId();

    // optional int32 mapperId = 4;
    /**
     * <code>optional int32 mapperId = 4;</code>
     */
    boolean hasMapperId();
    /**
     * <code>optional int32 mapperId = 4;</code>
     */
    int getMapperId();

    // optional string sourceOrTarget = 5;
    /**
     * <code>optional string sourceOrTarget = 5;</code>
     */
    boolean hasSourceOrTarget();
    /**
     * <code>optional string sourceOrTarget = 5;</code>
     */
    java.lang.String getSourceOrTarget();
    /**
     * <code>optional string sourceOrTarget = 5;</code>
     */
    com.google.protobuf.ByteString
        getSourceOrTargetBytes();

    // optional string trigger_id = 6;
    /**
     * <code>optional string trigger_id = 6;</code>
     */
    boolean hasTriggerId();
    /**
     * <code>optional string trigger_id = 6;</code>
     */
    java.lang.String getTriggerId();
    /**
     * <code>optional string trigger_id = 6;</code>
     */
    com.google.protobuf.ByteString
        getTriggerIdBytes();

    // optional string table_id = 7;
    /**
     * <code>optional string table_id = 7;</code>
     */
    boolean hasTableId();
    /**
     * <code>optional string table_id = 7;</code>
     */
    java.lang.String getTableId();
    /**
     * <code>optional string table_id = 7;</code>
     */
    com.google.protobuf.ByteString
        getTableIdBytes();

    // optional string CRUD_action = 8;
    /**
     * <code>optional string CRUD_action = 8;</code>
     */
    boolean hasCRUDAction();
    /**
     * <code>optional string CRUD_action = 8;</code>
     */
    java.lang.String getCRUDAction();
    /**
     * <code>optional string CRUD_action = 8;</code>
     */
    com.google.protobuf.ByteString
        getCRUDActionBytes();
  }
  /**
   * Protobuf type {@code gmapper.mysql.AdminQMsg}
   */
  public static final class AdminQMsg extends
      com.google.protobuf.GeneratedMessage
      implements AdminQMsgOrBuilder {
    // Use AdminQMsg.newBuilder() to construct.
    private AdminQMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AdminQMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AdminQMsg defaultInstance;
    public static AdminQMsg getDefaultInstance() {
      return defaultInstance;
    }

    public AdminQMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AdminQMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              action_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              adaptorType_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              adaptorId_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              mapperId_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              sourceOrTarget_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              triggerId_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              tableId_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              cRUDAction_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gmapper.mysql.ProtobufAdminQMsg.internal_static_gmapper_mysql_AdminQMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gmapper.mysql.ProtobufAdminQMsg.internal_static_gmapper_mysql_AdminQMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gmapper.mysql.ProtobufAdminQMsg.AdminQMsg.class, gmapper.mysql.ProtobufAdminQMsg.AdminQMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<AdminQMsg> PARSER =
        new com.google.protobuf.AbstractParser<AdminQMsg>() {
      public AdminQMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AdminQMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AdminQMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string action = 1;
    public static final int ACTION_FIELD_NUMBER = 1;
    private java.lang.Object action_;
    /**
     * <code>optional string action = 1;</code>
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string action = 1;</code>
     */
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          action_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string action = 1;</code>
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string adaptor_type = 2;
    public static final int ADAPTOR_TYPE_FIELD_NUMBER = 2;
    private java.lang.Object adaptorType_;
    /**
     * <code>optional string adaptor_type = 2;</code>
     */
    public boolean hasAdaptorType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string adaptor_type = 2;</code>
     */
    public java.lang.String getAdaptorType() {
      java.lang.Object ref = adaptorType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          adaptorType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string adaptor_type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAdaptorTypeBytes() {
      java.lang.Object ref = adaptorType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        adaptorType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 adaptor_id = 3;
    public static final int ADAPTOR_ID_FIELD_NUMBER = 3;
    private int adaptorId_;
    /**
     * <code>optional int32 adaptor_id = 3;</code>
     */
    public boolean hasAdaptorId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 adaptor_id = 3;</code>
     */
    public int getAdaptorId() {
      return adaptorId_;
    }

    // optional int32 mapperId = 4;
    public static final int MAPPERID_FIELD_NUMBER = 4;
    private int mapperId_;
    /**
     * <code>optional int32 mapperId = 4;</code>
     */
    public boolean hasMapperId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 mapperId = 4;</code>
     */
    public int getMapperId() {
      return mapperId_;
    }

    // optional string sourceOrTarget = 5;
    public static final int SOURCEORTARGET_FIELD_NUMBER = 5;
    private java.lang.Object sourceOrTarget_;
    /**
     * <code>optional string sourceOrTarget = 5;</code>
     */
    public boolean hasSourceOrTarget() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string sourceOrTarget = 5;</code>
     */
    public java.lang.String getSourceOrTarget() {
      java.lang.Object ref = sourceOrTarget_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sourceOrTarget_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sourceOrTarget = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSourceOrTargetBytes() {
      java.lang.Object ref = sourceOrTarget_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceOrTarget_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string trigger_id = 6;
    public static final int TRIGGER_ID_FIELD_NUMBER = 6;
    private java.lang.Object triggerId_;
    /**
     * <code>optional string trigger_id = 6;</code>
     */
    public boolean hasTriggerId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string trigger_id = 6;</code>
     */
    public java.lang.String getTriggerId() {
      java.lang.Object ref = triggerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          triggerId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string trigger_id = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTriggerIdBytes() {
      java.lang.Object ref = triggerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        triggerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string table_id = 7;
    public static final int TABLE_ID_FIELD_NUMBER = 7;
    private java.lang.Object tableId_;
    /**
     * <code>optional string table_id = 7;</code>
     */
    public boolean hasTableId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string table_id = 7;</code>
     */
    public java.lang.String getTableId() {
      java.lang.Object ref = tableId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tableId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string table_id = 7;</code>
     */
    public com.google.protobuf.ByteString
        getTableIdBytes() {
      java.lang.Object ref = tableId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string CRUD_action = 8;
    public static final int CRUD_ACTION_FIELD_NUMBER = 8;
    private java.lang.Object cRUDAction_;
    /**
     * <code>optional string CRUD_action = 8;</code>
     */
    public boolean hasCRUDAction() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string CRUD_action = 8;</code>
     */
    public java.lang.String getCRUDAction() {
      java.lang.Object ref = cRUDAction_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cRUDAction_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string CRUD_action = 8;</code>
     */
    public com.google.protobuf.ByteString
        getCRUDActionBytes() {
      java.lang.Object ref = cRUDAction_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cRUDAction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      action_ = "";
      adaptorType_ = "";
      adaptorId_ = 0;
      mapperId_ = 0;
      sourceOrTarget_ = "";
      triggerId_ = "";
      tableId_ = "";
      cRUDAction_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getActionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAdaptorTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, adaptorId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, mapperId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getSourceOrTargetBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getTriggerIdBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getTableIdBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getCRUDActionBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getActionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAdaptorTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, adaptorId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, mapperId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getSourceOrTargetBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getTriggerIdBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getTableIdBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getCRUDActionBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gmapper.mysql.ProtobufAdminQMsg.AdminQMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gmapper.mysql.ProtobufAdminQMsg.AdminQMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gmapper.mysql.ProtobufAdminQMsg.AdminQMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gmapper.mysql.ProtobufAdminQMsg.AdminQMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gmapper.mysql.ProtobufAdminQMsg.AdminQMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gmapper.mysql.ProtobufAdminQMsg.AdminQMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gmapper.mysql.ProtobufAdminQMsg.AdminQMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gmapper.mysql.ProtobufAdminQMsg.AdminQMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gmapper.mysql.ProtobufAdminQMsg.AdminQMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gmapper.mysql.ProtobufAdminQMsg.AdminQMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gmapper.mysql.ProtobufAdminQMsg.AdminQMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gmapper.mysql.AdminQMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements gmapper.mysql.ProtobufAdminQMsg.AdminQMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gmapper.mysql.ProtobufAdminQMsg.internal_static_gmapper_mysql_AdminQMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gmapper.mysql.ProtobufAdminQMsg.internal_static_gmapper_mysql_AdminQMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gmapper.mysql.ProtobufAdminQMsg.AdminQMsg.class, gmapper.mysql.ProtobufAdminQMsg.AdminQMsg.Builder.class);
      }

      // Construct using gmapper.mysql.ProtobufAdminQMsg.AdminQMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        action_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        adaptorType_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        adaptorId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        mapperId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        sourceOrTarget_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        triggerId_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        tableId_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        cRUDAction_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gmapper.mysql.ProtobufAdminQMsg.internal_static_gmapper_mysql_AdminQMsg_descriptor;
      }

      public gmapper.mysql.ProtobufAdminQMsg.AdminQMsg getDefaultInstanceForType() {
        return gmapper.mysql.ProtobufAdminQMsg.AdminQMsg.getDefaultInstance();
      }

      public gmapper.mysql.ProtobufAdminQMsg.AdminQMsg build() {
        gmapper.mysql.ProtobufAdminQMsg.AdminQMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gmapper.mysql.ProtobufAdminQMsg.AdminQMsg buildPartial() {
        gmapper.mysql.ProtobufAdminQMsg.AdminQMsg result = new gmapper.mysql.ProtobufAdminQMsg.AdminQMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.action_ = action_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.adaptorType_ = adaptorType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.adaptorId_ = adaptorId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.mapperId_ = mapperId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sourceOrTarget_ = sourceOrTarget_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.triggerId_ = triggerId_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.tableId_ = tableId_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.cRUDAction_ = cRUDAction_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gmapper.mysql.ProtobufAdminQMsg.AdminQMsg) {
          return mergeFrom((gmapper.mysql.ProtobufAdminQMsg.AdminQMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gmapper.mysql.ProtobufAdminQMsg.AdminQMsg other) {
        if (other == gmapper.mysql.ProtobufAdminQMsg.AdminQMsg.getDefaultInstance()) return this;
        if (other.hasAction()) {
          bitField0_ |= 0x00000001;
          action_ = other.action_;
          onChanged();
        }
        if (other.hasAdaptorType()) {
          bitField0_ |= 0x00000002;
          adaptorType_ = other.adaptorType_;
          onChanged();
        }
        if (other.hasAdaptorId()) {
          setAdaptorId(other.getAdaptorId());
        }
        if (other.hasMapperId()) {
          setMapperId(other.getMapperId());
        }
        if (other.hasSourceOrTarget()) {
          bitField0_ |= 0x00000010;
          sourceOrTarget_ = other.sourceOrTarget_;
          onChanged();
        }
        if (other.hasTriggerId()) {
          bitField0_ |= 0x00000020;
          triggerId_ = other.triggerId_;
          onChanged();
        }
        if (other.hasTableId()) {
          bitField0_ |= 0x00000040;
          tableId_ = other.tableId_;
          onChanged();
        }
        if (other.hasCRUDAction()) {
          bitField0_ |= 0x00000080;
          cRUDAction_ = other.cRUDAction_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gmapper.mysql.ProtobufAdminQMsg.AdminQMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gmapper.mysql.ProtobufAdminQMsg.AdminQMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string action = 1;
      private java.lang.Object action_ = "";
      /**
       * <code>optional string action = 1;</code>
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string action = 1;</code>
       */
      public java.lang.String getAction() {
        java.lang.Object ref = action_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          action_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string action = 1;</code>
       */
      public com.google.protobuf.ByteString
          getActionBytes() {
        java.lang.Object ref = action_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          action_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string action = 1;</code>
       */
      public Builder setAction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string action = 1;</code>
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = getDefaultInstance().getAction();
        onChanged();
        return this;
      }
      /**
       * <code>optional string action = 1;</code>
       */
      public Builder setActionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        action_ = value;
        onChanged();
        return this;
      }

      // optional string adaptor_type = 2;
      private java.lang.Object adaptorType_ = "";
      /**
       * <code>optional string adaptor_type = 2;</code>
       */
      public boolean hasAdaptorType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string adaptor_type = 2;</code>
       */
      public java.lang.String getAdaptorType() {
        java.lang.Object ref = adaptorType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          adaptorType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string adaptor_type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAdaptorTypeBytes() {
        java.lang.Object ref = adaptorType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          adaptorType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string adaptor_type = 2;</code>
       */
      public Builder setAdaptorType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        adaptorType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string adaptor_type = 2;</code>
       */
      public Builder clearAdaptorType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        adaptorType_ = getDefaultInstance().getAdaptorType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string adaptor_type = 2;</code>
       */
      public Builder setAdaptorTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        adaptorType_ = value;
        onChanged();
        return this;
      }

      // optional int32 adaptor_id = 3;
      private int adaptorId_ ;
      /**
       * <code>optional int32 adaptor_id = 3;</code>
       */
      public boolean hasAdaptorId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 adaptor_id = 3;</code>
       */
      public int getAdaptorId() {
        return adaptorId_;
      }
      /**
       * <code>optional int32 adaptor_id = 3;</code>
       */
      public Builder setAdaptorId(int value) {
        bitField0_ |= 0x00000004;
        adaptorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 adaptor_id = 3;</code>
       */
      public Builder clearAdaptorId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        adaptorId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 mapperId = 4;
      private int mapperId_ ;
      /**
       * <code>optional int32 mapperId = 4;</code>
       */
      public boolean hasMapperId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 mapperId = 4;</code>
       */
      public int getMapperId() {
        return mapperId_;
      }
      /**
       * <code>optional int32 mapperId = 4;</code>
       */
      public Builder setMapperId(int value) {
        bitField0_ |= 0x00000008;
        mapperId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 mapperId = 4;</code>
       */
      public Builder clearMapperId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        mapperId_ = 0;
        onChanged();
        return this;
      }

      // optional string sourceOrTarget = 5;
      private java.lang.Object sourceOrTarget_ = "";
      /**
       * <code>optional string sourceOrTarget = 5;</code>
       */
      public boolean hasSourceOrTarget() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string sourceOrTarget = 5;</code>
       */
      public java.lang.String getSourceOrTarget() {
        java.lang.Object ref = sourceOrTarget_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sourceOrTarget_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sourceOrTarget = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSourceOrTargetBytes() {
        java.lang.Object ref = sourceOrTarget_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourceOrTarget_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sourceOrTarget = 5;</code>
       */
      public Builder setSourceOrTarget(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sourceOrTarget_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sourceOrTarget = 5;</code>
       */
      public Builder clearSourceOrTarget() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sourceOrTarget_ = getDefaultInstance().getSourceOrTarget();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sourceOrTarget = 5;</code>
       */
      public Builder setSourceOrTargetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sourceOrTarget_ = value;
        onChanged();
        return this;
      }

      // optional string trigger_id = 6;
      private java.lang.Object triggerId_ = "";
      /**
       * <code>optional string trigger_id = 6;</code>
       */
      public boolean hasTriggerId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string trigger_id = 6;</code>
       */
      public java.lang.String getTriggerId() {
        java.lang.Object ref = triggerId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          triggerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string trigger_id = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTriggerIdBytes() {
        java.lang.Object ref = triggerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          triggerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string trigger_id = 6;</code>
       */
      public Builder setTriggerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        triggerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string trigger_id = 6;</code>
       */
      public Builder clearTriggerId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        triggerId_ = getDefaultInstance().getTriggerId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string trigger_id = 6;</code>
       */
      public Builder setTriggerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        triggerId_ = value;
        onChanged();
        return this;
      }

      // optional string table_id = 7;
      private java.lang.Object tableId_ = "";
      /**
       * <code>optional string table_id = 7;</code>
       */
      public boolean hasTableId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string table_id = 7;</code>
       */
      public java.lang.String getTableId() {
        java.lang.Object ref = tableId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          tableId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string table_id = 7;</code>
       */
      public com.google.protobuf.ByteString
          getTableIdBytes() {
        java.lang.Object ref = tableId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tableId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string table_id = 7;</code>
       */
      public Builder setTableId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        tableId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string table_id = 7;</code>
       */
      public Builder clearTableId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        tableId_ = getDefaultInstance().getTableId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string table_id = 7;</code>
       */
      public Builder setTableIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        tableId_ = value;
        onChanged();
        return this;
      }

      // optional string CRUD_action = 8;
      private java.lang.Object cRUDAction_ = "";
      /**
       * <code>optional string CRUD_action = 8;</code>
       */
      public boolean hasCRUDAction() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string CRUD_action = 8;</code>
       */
      public java.lang.String getCRUDAction() {
        java.lang.Object ref = cRUDAction_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          cRUDAction_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string CRUD_action = 8;</code>
       */
      public com.google.protobuf.ByteString
          getCRUDActionBytes() {
        java.lang.Object ref = cRUDAction_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cRUDAction_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string CRUD_action = 8;</code>
       */
      public Builder setCRUDAction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        cRUDAction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string CRUD_action = 8;</code>
       */
      public Builder clearCRUDAction() {
        bitField0_ = (bitField0_ & ~0x00000080);
        cRUDAction_ = getDefaultInstance().getCRUDAction();
        onChanged();
        return this;
      }
      /**
       * <code>optional string CRUD_action = 8;</code>
       */
      public Builder setCRUDActionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        cRUDAction_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gmapper.mysql.AdminQMsg)
    }

    static {
      defaultInstance = new AdminQMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gmapper.mysql.AdminQMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gmapper_mysql_AdminQMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gmapper_mysql_AdminQMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021PBAdminQMsg.proto\022\rgmapper.mysql\"\252\001\n\tA" +
      "dminQMsg\022\016\n\006action\030\001 \001(\t\022\024\n\014adaptor_type" +
      "\030\002 \001(\t\022\022\n\nadaptor_id\030\003 \001(\005\022\020\n\010mapperId\030\004" +
      " \001(\005\022\026\n\016sourceOrTarget\030\005 \001(\t\022\022\n\ntrigger_" +
      "id\030\006 \001(\t\022\020\n\010table_id\030\007 \001(\t\022\023\n\013CRUD_actio" +
      "n\030\010 \001(\tB\"\n\rgmapper.mysqlB\021ProtobufAdminQ" +
      "Msg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_gmapper_mysql_AdminQMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_gmapper_mysql_AdminQMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gmapper_mysql_AdminQMsg_descriptor,
              new java.lang.String[] { "Action", "AdaptorType", "AdaptorId", "MapperId", "SourceOrTarget", "TriggerId", "TableId", "CRUDAction", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
